# fly.toml app configuration file generated for template-client on 2024-02-27T23:51:32+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'template-client'
primary_region = 'arn'

[build.args]
  TARGET = 'production'
  JWT_SECRET = 'JWT_SECRET'
  PUBLIC_DIRECTUS_URL = 'https://template-directus.fly.dev'
  PUBLIC_AUTH_URL = 'https://template-service-users.fly.dev'
  USERS_URI = 'template-service-users.fly.dev:3002'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
