# fly.toml app configuration file generated for template-service-profile on 2024-03-05T21:22:25+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'template-service-profile'
primary_region = 'arn'

[build]

[env]
  CERT_PATH = '/etc/letsencrypt/live/example.com/fullchain.pem'
  GRPC_PORT = '3003'
  KEY_PATH = '/etc/letsencrypt/live/example.com/privkey.pem'
  LOG_LEVEL = 'info'
  TLS = 'false'

[[services]]
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  internal_port = 3003

[[services.ports]]
    port = 3003
    handlers = ['tls']

    [services.ports.tls_options]
      alpn = ['h2']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
