# fly.toml app configuration file generated for service-users on 2024-02-27T23:23:57+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'service-users'
primary_region = 'arn'

[env]
  LOG_LEVEL = 'info'
  HTTP_PORT = 3001
  GRPC_PORT = 3002
  COOKIE_DOMAIN = 'localhost'
  CLIENT_URL = 'https://template-client.fly.dev'
  SERVER_HTTP = 'https://service-users.fly.dev'
  REDIS_URL = 'redis://default:0bcf7cffff454f00a751247593d9d994@fly-rusve-redis.upstash.io:6379'
  REDIS_PASSWORD = 12345
  TLS = 'false'
  CERT_PATH = '/etc/letsencrypt/live/example.com/fullchain.pem'
  KEY_PATH = '/etc/letsencrypt/live/example.com/privkey.pem'
  JWT_SECRET = '${JWT_SECRET}'
  STRIPE_API_KEY = '${STRIPE_API_KEY}'
  STRIPE_PRICE_ID = 'price_1OmhP6HRNcZGXxTidRkfuTFr'
  GOOGLE_CLIENT_ID = '${GOOGLE_CLIENT_ID}'
  GOOGLE_CLIENT_SECRET = '${GOOGLE_CLIENT_SECRET}'
  GITHUB_CLIENT_ID = '${GITHUB_CLIENT_ID}'
  GITHUB_CLIENT_SECRET = '${GITHUB_CLIENT_SECRET}'

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  internal_port = 3002
  [[services.ports]]
    handlers = ["tls"]
    port = 3002
    tls_options = { "alpn" = ["h2"] }

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
