services:
  svelte:
    container_name: svelte
    build:
      context: ./svelte
      target: dev
      args:
        TARGET: development
        PUBLIC_AUTH_HTTP: http://localhost:3001
        DIRECTUS_URL: http://directus:8055
    depends_on:
      - directus
    volumes:
      - ./svelte/src:/client/src
      - ./svelte/.svelte-kit:/client/.svelte-kit
    ports:
      - 3000:3000
    command: sh -c "npm run dev"

  go:
    container_name: go
    working_dir: /server
    build:
      context: ./go
      target: dev
    volumes:
      - ./go:/server
    ports:
      - 3001:3001
      - 3002:3002
    environment:
      LOG_LEVEL: debug
      HTTP_PORT: 3001
      GRPC_PORT: 3002
      COOKIE_DOMAIN: localhost
      CLIENT_URL: http://localhost:3000
      SERVER_HTTP: http://localhost:3001
      REDIS_URL: redis:6379
      REDIS_PASSWORD: 12345
      TLS: "false"
      CERT_PATH: /etc/letsencrypt/live/example.com/fullchain.pem
      KEY_PATH: /etc/letsencrypt/live/example.com/privkey.pem
      JWT_SECRET: ${JWT_SECRET}
      STRIPE_API_KEY: ${STRIPE_API_KEY}
      STRIPE_PRICE_ID: price_1OmhP6HRNcZGXxTidRkfuTFr
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET} 
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
    command: sh -c "go run /server/."

  redis:
    container_name: powerit-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass 12345

  directus:
    container_name: directus
    build:
      context: ./directus
    ports:
      - 8055:8055
    volumes:
      - ./directus/database:/directus/database
      - ./directus/uploads:/directus/uploads
      - ./directus/extensions:/directus/extensions
    environment:
      PUBLIC_URL: http://0.0.0.0:8055
      KEY: jsklrhqikrgbqhujfgqlrqgyuieroqyiureqi
      SECRET: sqhlasjfghassdguqwgfbjhqvrjhqwerfqwjevgqwjegqwje
      ADMIN_EMAIL: admin@gmail.com
      ADMIN_PASSWORD: A1m2n
      DB_CLIENT: sqlite3
      DB_FILENAME: /directus/database/data.db
      EMAIL_VERIFY_SETUP: true
      EMAIL_TRANSPORT: sendgrid
      EMAIL_FROM: email@upsend.app
      EMAIL_SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      WEBSOCKETS_ENABLED: true
      # CACHE_ENABLED: "true"
      # CACHE_STORE: "redis"
      # REDIS: "redis://cache:6379"
