services:
  client:
    container_name: template-client
    build:
      context: ./client
      target: dev
      args:
        TARGET: development
        JWT_SECRET: ${JWT_SECRET}
        PUBLIC_DIRECTUS_URL: https://template-directus.fly.dev
        PUBLIC_AUTH_URL: http://localhost:3001
        AUTH_URI: service-auth:3002
        PROFILE_URI: service-profile:3003
    volumes:
      - ./client/src:/client/src
      - ./client/.svelte-kit:/client/.svelte-kit
    ports:
      - 3000:3000
    command: sh -c "npm run dev"

  service-auth:
    container_name: template-service-auth
    working_dir: /server
    build:
      context: ./service-auth
      target: dev
    volumes:
      - ./service-auth:/server
    ports:
      - 3001:3001
      - 3002:3002
    environment:
      LOG_LEVEL: debug
      HTTP_PORT: 3001
      GRPC_PORT: 3002
      COOKIE_DOMAIN: localhost
      CLIENT_URL: http://localhost:3000
      SERVER_HTTP: http://localhost:3001
      REDIS_URL: redis:6379
      REDIS_PASSWORD: 12345
      TLS: "false"
      CERT_PATH: /etc/letsencrypt/live/example.com/fullchain.pem
      KEY_PATH: /etc/letsencrypt/live/example.com/privkey.pem
      JWT_SECRET: ${JWT_SECRET}
      STRIPE_API_KEY: ${STRIPE_API_KEY}
      STRIPE_PRICE_ID: ${STRIPE_PRICE_ID}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      TURSO_URL: ${TURSO_AUTH_URL}
    command: sh -c "go run /server/."

  redis:
    container_name: template-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass 12345

  service-profile:
    container_name: template-service-profile
    working_dir: /server
    build:
      context: ./service-profile
      target: dev
    volumes:
      - ./service-profile:/server
    environment:
      LOG_LEVEL: debug
      GRPC_PORT: 3003
      TLS: "false"
      CERT_PATH: /etc/letsencrypt/live/example.com/fullchain.pem
      KEY_PATH: /etc/letsencrypt/live/example.com/privkey.pem
      JWT_SECRET: ${JWT_SECRET}
      TURSO_URL: ${TURSO_PROFILE_URL}
    command: sh -c "go run /server/."
