services:
  directus:
    container_name: directus
    build:
      context: ./directus
    ports:
      - 8055:8055
    volumes:
      - ./directus/database:/directus/database
      - ./directus/uploads:/directus/uploads
      - ./directus/extensions:/directus/extensions
    environment:
      KEY: jsklrhqikrgbqhujfgqlrqgyuieroqyiureqi
      SECRET: sqhlasjfghassdguqwgfbjhqvrjhqwerfqwjevgqwjegqwje
      ADMIN_EMAIL: admin@gmail.com
      ADMIN_PASSWORD: A1m2n
      DB_CLIENT: sqlite3
      DB_FILENAME: /directus/database/data.db
      EMAIL_VERIFY_SETUP: true
      EMAIL_TRANSPORT: sendgrid
      EMAIL_FROM: email@upsend.app
      EMAIL_SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      WEBSOCKETS_ENABLED: true
      PUBLIC_URL: http://0.0.0.0:8055
      # CACHE_ENABLED: "true"
      # CACHE_STORE: "redis"
      # REDIS: "redis://cache:6379"

  svelte:
    container_name: svelte
    build:
      context: ./svelte
    depends_on:
      - directus
    volumes:
      - ./svelte/src:/client/src
      - ./svelte/.svelte-kit:/client/.svelte-kit
    ports:
      - 3000:3000
