# fly.toml app configuration file generated for template-directus on 2024-02-01T16:21:36+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'template-directus'
primary_region = 'arn'

[env]
  KEY = "jsklrhqikrgbqhujfgqlrqgyuieroqyiureqi"
  SECRET = "sqhlasjfghassdguqwgfbjhqvrjhqwerfqwjevgqwjegqwje"
  ADMIN_EMAIL = "admin@gmail.com"
  ADMIN_PASSWORD = "A1m2n"
  DB_CLIENT = "pg"
  CACHE_ENABLED = "true"

[build]

[http_service]
  internal_port = 8055
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
