# fly.toml app configuration file generated for template-directus on 2024-03-03T10:00:14+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'template-directus'
primary_region = 'arn'

[build]

[env]
  ADMIN_EMAIL = 'admin@gmail.com'
  ADMIN_PASSWORD = 'A1m2n'
  DB_CLIENT = 'sqlite3'
  DB_FILENAME = '/data/data.db'
  KEY = 'jsklrhqikrgbqhujfgqlrqgyuieroqyiureqi'
  PUBLIC_URL = 'https://template-directus.fly.dev'
  SECRET = 'sqhlasjfghassdguqwgfbjhqvrjhqwerfqwjevgqwjegqwje'
  STORAGE_LOCAL_ROOT = '/data'
  EMAIL_VERIFY_SETUP = true
  EMAIL_TRANSPORT = 'sendgrid'
  EMAIL_FROM = 'email@upsend.app'
  # EMAIL_SENDGRID_API_KEY = set using fly secrets set EMAIL_SENDGRID_API_KEY=your-api-key

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 8055
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
