# fly.toml app configuration file generated for template-directus on 2024-02-01T16:21:36+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'template-directus'
primary_region = 'arn'

[env]
  KEY = "jsklrhqikrgbqhujfgqlrqgyuieroqyiureqi"
  SECRET = "sqhlasjfghassdguqwgfbjhqvrjhqwerfqwjevgqwjegqwje"
  ADMIN_EMAIL = "admin@gmail.com"
  ADMIN_PASSWORD = "A1m2n"
  DB_CLIENT = 'sqlite3'
  DB_FILENAME = '/directus/database/data.db'

[mounts]
  source = 'directus'
  destination = '/directus'

[http_service]
  internal_port = 8055
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
