# fly.toml app configuration file generated for template-service-users on 2024-02-28T11:17:32+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'template-service-users'
primary_region = 'arn'

[build]

[env]
  CERT_PATH = '/etc/letsencrypt/live/example.com/fullchain.pem'
  CLIENT_URL = 'https://template-client.fly.dev'
  COOKIE_DOMAIN = 'template-client.fly.dev'
  GITHUB_CLIENT_ID = 'GITHUB_CLIENT_ID'
  GITHUB_CLIENT_SECRET = 'GITHUB_CLIENT_SECRET'
  GRPC_PORT = '3002'
  HTTP_PORT = '3001'
  JWT_SECRET = 'JWT_SECRET'
  KEY_PATH = '/etc/letsencrypt/live/example.com/privkey.pem'
  LOG_LEVEL = 'info'
  REDIS_URL = 'fly-rusve-redis.upstash.io:6379'
  SERVER_HTTP = 'https://template-service-users.fly.dev'
  STRIPE_API_KEY = 'STRIPE_API_KEY'
  STRIPE_PRICE_ID = 'price_1OmhP6HRNcZGXxTidRkfuTFr'
  TLS = 'false'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = ''
  internal_port = 3002

[[services.ports]]
    port = 3002
    handlers = ['tls']

    [services.ports.tls_options]
      alpn = ['h2']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
