# fly.toml app configuration file generated for template-service-auth on 2024-03-05T20:51:09+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'template-service-auth'
primary_region = 'arn'

[build]

[env]
  CERT_PATH = '/etc/letsencrypt/live/example.com/fullchain.pem'
  CLIENT_URL = 'https://template-client.fly.dev'
  GRPC_PORT = '3002'
  HTTP_PORT = '3001'
  KEY_PATH = '/etc/letsencrypt/live/example.com/privkey.pem'
  LOG_LEVEL = 'info'
  REDIS_URL = 'fly-template-service-auth-redis.upstash.io:6379'
  SERVER_HTTP = 'https://template-service-auth.fly.dev'
  TLS = 'false'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = ''
  internal_port = 3002

[[services.ports]]
    port = 3002
    handlers = ['tls']

    [services.ports.tls_options]
      alpn = ['h2']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
