name: Pull Request

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-client:
    uses: ./.github/workflows/lint-client.yml
    secrets:
      GSAP_TOKEN: ${{ secrets.GSAP_TOKEN }}
